---
- debug:
    msg: "{{ ansible_distribution }}"

- name: Install required packages
  become: True
  become_method: sudo
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
    - ca-certificates
    - curl
    - gnupg-agent
    - lsb-release

# Ubuntu, Linux Mint, Pop!_OS

- name: Add ubuntu apt signing key for Docker
  become: True
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
    ansible_distribution in ("Ubuntu", "Linux Mint", "Pop!_OS")

# Debian

- name: Add debian apt signing key for Docker
  become: True
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present     
  when:
    ansible_distribution == "Debian"

- name: Add Debian apt repository for Docker
  become: True
  become_method: sudo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present
  when:
    ansible_distribution == "Debian"

# Ubuntu, Linux Mint, Pop!_OS, Debian

- name: Install docker
  become: True
  become_method: sudo
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      # - docker
      - docker.io
      # - docker-ce-cli 
      # - containerd.io 
  notify:
    - docker started
  when:
    ansible_distribution in ("Ubuntu", "Linux Mint", "Pop!_OS", "Debian")

#  Fedora, CentOS

- name: Install python-dnf module
  become: True
  become_method: sudo
  dnf:
    name: python-dnf
    state: present
  when:
    ansible_distribution == "Fedora" or ansible_distribution == "CentOS"

- name: Install dnf-plugins-core to manage DNF repository
  become: True
  become_method: sudo
  dnf:
    name: dnf-plugins-core
    state: present
  when:
    ansible_distribution == "Fedora" or ansible_distribution == "CentOS"

- name: Add docker repo
  become: True
  become_method: sudo
  shell: dnf config-manager --add-repo 'https://download.docker.com/linux/fedora/docker-ce.repo'
  when:
    ansible_distribution == "Fedora"

- name: Add docker repo
  become: True
  become_method: sudo

  shell: dnf config-manager --add-repo 'https://download.docker.com/linux/centos/docker-ce.repo'
  when:
    ansible_distribution == "CentOS"

- name: Get the username for docker
  become: false
  local_action: command whoami
  register: username_on_the_host
  
- debug: 
    msg: "Current user: {{ username_on_the_host.stdout }}"

- name: Enable docker deamon
  become: True
  become_method: sudo
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    masked: no

- name: Add user to docker group
  become: True
  become_method: sudo
  ansible.builtin.user:
    name: "{{ username_on_the_host.stdout }}"
    groups: docker
    append: yes
  notify:
    - docker restarted

# - name: Check directory /etc/docker
#   stat: 
#     path: /etc/docker
#   register: daemon_dir

# - name: Copy daemon.json with predefined configuration
#   ansible.builtin.copy:
#     src: daemon.json
#     dest: /etc/docker/daemon.json
#   when: daemon_dir.stat.isdir
#   notify:
#     - docker restart
