# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"

IMAGE_NAME = "enzzito/myxubuntu2204-gui"
BOX_VERSION = "0.1"
CLIENT_IP = "192.168.56.20"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.ssh.insert_key = "true"
  config.ssh.forward_agent = "true"

  config.vm.define "torcs-lubuntu" do |client|
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
      vb.gui = true
    end
      
    client.vm.box = IMAGE_NAME
    client.vm.box_version = BOX_VERSION          
    client.vm.network "private_network", ip: CLIENT_IP
    config.vm.network "forwarded_port", guest: 22, host: 2222
    client.vm.hostname = "torcs-lubuntu"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    ansible.playbook = "../ansible/playbooks/playbook-torcs-server.yaml"
    host_key_checking = "true"

    ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/env python3",
        ansible_verbose: "v",
        ansible_order: "sorted",
    }

    ansible.groups = {
      "clients" => ["torcs-lubuntu"],
      "servers" => ["torcs-lubuntu"],
      "torcs:children" => ["clients", "servers"],
    }

  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    
    ansible.playbook = "../ansible/playbooks/playbook-torcs-client.yaml"
    host_key_checking = "false"

    ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/env python3",
        ansible_verbose: "v",
        ansible_order: "sorted"
    }            

    ansible.groups = {
      "clients" => ["torcs-lubuntu"],
      "torcs:children" => ["clients", "servers"],
    }

  end

end