# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"
WORKSPACE = "../ansible"

SERVER_IMAGE_NAME = "gusztavvargadr/ubuntu-desktop"
SERVER_BOX_VERSION = "2004.0.2304"
SERVER_IP = "192.168.56.20"

CLIENT_IMAGE_NAME = "ubuntu/xenial64"
CLIENT_BOX_VERSION = "20211001.0.0"
CLIENT_IP = "192.168.56.21"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.ssh.insert_key = "true"
  config.ssh.forward_agent = "true"

  config.vm.define "torcs-server" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
      vb.gui = true
    end
      
    server.vm.box = SERVER_IMAGE_NAME
    server.vm.box_version = SERVER_BOX_VERSION          
    server.vm.network "private_network", ip: SERVER_IP
    # server.vm.network "forwarded_port", guest: 22, host: 2222
    server.vm.hostname = "torcs-server"

  end

  config.vm.define "torcs-client" do |client|
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = false
    end
      
    client.vm.box = CLIENT_IMAGE_NAME
    client.vm.box_version = CLIENT_BOX_VERSION          
    client.vm.network "private_network", ip: CLIENT_IP
    # config.vm.network "forwarded_port", guest: 22, host: 2223
    client.vm.hostname = "torcs-ubuntu"
    client.vm.provision "shell", inline: "sudo apt-add-repository ppa:ansible/ansible"
    client.vm.synced_folder WORKSPACE, "/workspace"

  end
    
  # config.vm.provision "ansible" do |ansible|
  #   ansible.limit = 'all'
  #   ansible.playbook = "../ansible/playbooks/playbook-torcs-server.yaml"
  #   host_key_checking = "true"
  #   ansible.compatibility_mode = "2.0"        

  #   ansible.extra_vars = {
  #       ansible_python_interpreter: "/usr/bin/env python3",
  #       ansible_verbose: "v",
  #       ansible_order: "sorted"
  #   }

  #   ansible.groups = {
  #     "clients" => ["torcs-ubuntu"],
  #     "servers" => ["torcs-ubuntu"],
  #     "torcs:children" => ["clients", "servers"]
  #   }

  # end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.limit = 'all'
    
  #   ansible.playbook = "../ansible/playbooks/playbook-torcs-client.yaml"
  #   host_key_checking = "false"

  #   ansible.extra_vars = {
  #       ansible_python_interpreter: "/usr/bin/env python3",
  #       ansible_verbose: "v",
  #       ansible_order: "sorted"
  #   }            

  #   ansible.groups = {
  #     "clients" => ["torcs-ubuntu"],
  #     "torcs:children" => ["clients", "servers"],
  #   }

  # end

end